### ISSUE TITLE
automation for converting csv files to xlsx

### ISSUE THREAD

**Issue by OriHoch** [hasadna/datacity-k8s#117]
should have a process which automatically adds an xlsx resource for every csv resource - to allow easier opening of the files (some people might have problems opening csv files)

**Comment by niryariv** [comment]
basically it's the same file with an .xslx extension?

**Comment by OriHoch** [comment]
Yes, for every csv file we will add an xlsx file with the same data

**Comment by niryariv** [comment]
sounds good. moving to TODO

**Comment by OriHoch** [comment]
done, daily task in dgp handles this and adds an xlsx resource for every csv resource, e.g. - https://kfar-saba.datacity.org.il/dataset/schools

**Comment by niryariv** [comment]
@OriHoch 

1. Looks like the data preview for the xlsx file is [empty](https://kfar-saba.datacity.org.il/dataset/schools/resource/a8320041-23f7-4a6c-8a7a-49da8aa1740f). Can we fix this?

2. Would it make sense to add it to the upload process instead of a background task, is it too time consuming? So that the user can know about the xlsx file and check it as soon as they upload

**Comment by OriHoch** [comment]
thanks, 

1. opened a new issue - #130 
2. handled in this issue, added your comment there - #129
