### ISSUE TITLE
הוספת תחום סביבה לראשון לציון וירושלים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#140]
אייקון וכו כאן:
https://maale-adummim.datacity.org.il/group/environment

**Comment by eilanabenish** [comment]
בוצע

**Comment by niryariv** [comment]
התחום מופיע בלי אייקון:

https://rishonlezion.datacity.org.il/group/environment
https://jerusalem.datacity.org.il/group/environment

אני אתקן את ראשון לציון בעצמי כי עוד מעט יש פגישה איתם, טפלי בבקשה בירושלים

**Comment by eilanabenish** [comment]
יישמתי בירושלים למעט הקישור עם המפה. נדבר על זה מחר      ובכבוד רב | Sincerely,אילנה בניש מורשה נגישות שירות 2200 | Eilana Benish, service Accessibility authorized (2200) ניהול פרויקטים – נגישות ושמישות אינטרנט וטכנולוגיות מידע  | Projects manager – Accessibility & usability on internet and ICT📱 +972-50-7100367 | 📧 benish.ilana@gmail.com   מאת: Nir Yarivנשלח: יום רביעי 25 נובמבר 2020 09:00אל: hasadna/datacity-k8sעותק: eilanabenish; Assignנושא: Re: [hasadna/datacity-k8s] הוספת תחום סביבה לראשון לציון וירושלים (#140) התחום מופיע בלי אייקון:https://rishonlezion.datacity.org.il/group/environmenthttps://jerusalem.datacity.org.il/group/environmentאני אתקן את ראשון לציון בעצמי כי עוד מעט יש פגישה איתם, טפלי בבקשה בירושלים—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by niryariv** [comment]
@eilanabenish לא מבין מה כתוב כאן.. בכל מקרה ככל שאני רואה בירושלים עדיין אין אייקון
