### ISSUE TITLE
המערכת לא יוצרת קובץ גאוגרפי

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#192]
1. User uploads CSV + XLS here: https://kfar-saba.datacity.org.il/dataset/mazlemot
2. The system creates an extra XLS file (handling this in #191)
3. But doesn't create a GeoJSON file, although the CSV has X/Y fields

**Comment by OriHoch** [comment]
the problem was that the resource was missing the datastore schema (can be seen under the resource table with title מילון מונחים), this was fixed for this resource by manually reuploading to datastore (edit resource -> datastore -> העלאה למחסן הנתונים)

once the schema was created (מילון מונחים is displayed), I manually ran the geojson processing for kfar saba in dgp app and now the geojson resource was created

continue on #193 to fix the general datastore error
